# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kYBkr7oVnIZoPkQaw98AbYWN7OaKxn7
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("batch 4 dataset-housing data (1).csv")
df['date'] = pd.to_datetime(df['date'], dayfirst=True)
price_trend = df.groupby('date') ['average_price'].mean()
plt.plot(price_trend.index, price_trend.values)
plt.xlabel("Date")
plt.ylabel("Average Price")
plt.title("Average House Price Over Time")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df= pd.read_csv("batch 4 dataset-housing data (1).csv")
plt.scatter(df['houses_sold'], df['average_price'])
plt.xlabel("Houses Sold")
plt.ylabel("Average Price")
plt.title("Houses Sold vs Average Price")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("batch 4 dataset-housing data (1).csv")
area_price = df.groupby ('area')['average_price'].mean()
plt.bar(area_price.index, area_price.values)
plt.xticks(rotation=90)